name: govulncheck

on:
  schedule:
    # Run every Monday
    - cron: '0 0 * * 1'

env:
  GO_VERSION: "^1.22"

permissions:
  contents: read

jobs:
  ci-security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        name: Checkout code
      - name: Set up Go 1.x
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install govulncheck binary
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run security checks
        run: |
          govulncheck ./...
